-- Supabase setup script for CMSVize Project

-- 1. Create testimonials table
CREATE TABLE IF NOT EXISTS testimonials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  country TEXT NOT NULL,
  visa_type TEXT,
  comment TEXT,
  likes INT DEFAULT 0,
  comments_count INT DEFAULT 0,
  time_ago TEXT,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Create site_settings table
CREATE TABLE IF NOT EXISTS site_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT DEFAULT 'CMSVize | Avrupa Kapısı Açılıyor',
  phone TEXT DEFAULT '905459918268',
  whatsapp TEXT DEFAULT '905459918268',
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Initialize site_settings with default values
INSERT INTO site_settings (id, title, phone, whatsapp)
VALUES (1, 'CMSVize | Avrupa Kapısı Açılıyor', '905459918268', '905459918268')
ON CONFLICT (id) DO NOTHING;
